### ISSUE TITLE
[bug] Bottom buttons cut off from screen

### ISSUE THREAD

**Issue by CerebrumCaelum** [boltcard/bolt-card-pos#12]
Bottom bar of the digits (0 . C) is cut off from the screen on older android phones with smaller screens. For example on a Samsung Galaxy S6. Since older phones might be more likely repurposed for PoS devices it might be a good idea to make this app compatible with smaller screens. 

- v0.0.3
- Samsung Galaxy S6
- Android 7.0
![pos](https://github.com/boltcard/bolt-card-pos/assets/84624366/97c24376-7d3a-46f0-b094-753f308959c9)

**Comment by robertclarkson** [comment]
Thanks for the bug report. What is the screen resolution of your device?

**Comment by robertclarkson** [comment]
I've submitted a new release to the play store should fix this.

**Comment by CerebrumCaelum** [comment]
Great! Just verified and its working much better.
