### ISSUE TITLE
[BUG] API invoice error - When fiat value is below 1

### ISSUE THREAD

**Issue by CerebrumCaelum** [boltcard/bolt-card-pos#14]
Add invoice error
API unexpected response:
["detail""Failed to create invoice"]

- 0.0.4
- Android 9

How to reproduce:

1. Set currency to EUR / USD
2. Set invoice to EUR / USD
3. Enter any fiat value below 1 Euro, for example 0.1 Euro
4. Press Invoice button
5. Error will show

Value above 1 Euro work fine

**Comment by robertclarkson** [comment]
This is fixed in https://github.com/boltcard/bolt-card-pos/releases/tag/v0.0.5
