### ISSUE TITLE
Request PIN number at Point of sale

### ISSUE THREAD

**Issue by robertclarkson** [boltcard/bolt-card-pos#15]
As per draft LUD 
https://github.com/bitcoin-ring/luds/blob/withdraw-pin/xx.md
https://github.com/lnurl/luds/pull/200/files#diff-b03763e9ce2c6b65c01f6808159d6fea9a31cfdda3482bd71dee60cf117a4a5a

if the LNURL callback has parameter &pinLimit=X

The pinLimit value must be a positive integer (including 0) with a maximum of 15 digits. If the pinLimit property is present and a WALLET (Point of Sale) intends to withdraw an amount equal to or greater than the pinLimit value (in millisatoshis) it must first acquire a PIN from the user (customer) and then add it as pin=<pin> to the query string of the callback URL to authorize the withdrawal.

**Comment by chloehjung15** [comment]
#16 #
