### ISSUE TITLE
Add FIAT currency conversions

### ISSUE THREAD

**Issue by robertclarkson** [boltcard/bolt-card-pos#6]
Would be good to allow the user to type in an amount in a FIAT currency and to auto convert to sats.

Check the BlueWallet code for how they do this. 

Might need a backend servce, wonder if there is something in the LNBits LNDHub extension to do this?

**Comment by PeterRounce** [comment]
[BTCPay Server rate providers here](https://github.com/btcpayserver/btcpayserver/tree/master/BTCPayServer.Rating/Providers)

e.g. https://api.coingecko.com/api/v3/exchange_rates

Rates probably update every 15 minutes so could be cached for a while - maybe 5 minutes - for PoS performance.

**Comment by robertclarkson** [comment]
This is done
