### ISSUE TITLE
screen contrast is sometimes unreadable (dark mode)

### ISSUE THREAD

**Issue by PeterRounce** [boltcard/bolt-card-pos#9]
Having `dark mode` switched on (and sometimes with it off) I get displays with unreadable contrast.

unreadable
![pos-dark-1-small](https://user-images.githubusercontent.com/99006127/229269905-51c89153-f0c4-44d2-9140-9d49ce20b97e.jpg)

normal
![pos-dark-2-small](https://user-images.githubusercontent.com/99006127/229269907-69d4f5f8-3a25-4ae2-a6be-77fe32093f10.jpg)

**Comment by PeterRounce** [comment]
looks like it is caused by dark mode being enabled when the app is launched
(colour theme stays the same if the app is in standby)

**Comment by robertclarkson** [comment]
Fixed
